name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'     # or your actual version (3.4.4 shows in logs)
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman --no-pager -i config/brakeman.ignore
